knocklabs/javascript

- examples/client-example/package.json
- examples/nextjs-example/package.json
- package.json
- packages/client/package.json
- packages/eslint-config/package.json
- packages/react-core/package.json
- packages/react/package.json
- yarn.lock
Adds [manypkg](https://github.com/Thinkmill/manypkg), a tool to automatically sync dependency versions across the monorepo. Recommended by @kylemcd and the [Turborepo docs](https://turbo.build/repo/docs/handbook/troubleshooting).
> chore: add postinstall script to sync package versions across packages

- packages/client/package.json
- packages/client/test/knock.test.ts
- packages/client/vitest.config.mts
- yarn.lock
Adds Vitest to the client-js library and very basic tests. Will set up CI/CD in a follow up PR.
> chore: add tests to client-js

- .changeset/rotten-hairs-bathe.md
- packages/client/package.json
- yarn.lock
Adds `@babel/runtime` as a dependency since it's required by the [babel-plugin-transform-runtime](https://babeljs.io/docs/babel-plugin-transform-runtime) plugin we use.
> fix: add @babel/runtime dependency

- .changeset/three-kangaroos-push.md
- packages/react/package.json
- yarn.lock
> fix: update popperjs dependency

- .changeset/popular-days-worry.md
- packages/eslint-config/package.json
When installing `@knocklabs/eslint-config` because the dependencies are set to `devDependencies`, they're not installed along with the config. This means each of those dependencies would need to be installed on their own. 
This moves these `devDependencies` to `dependencies` to make install smoother.
> fix: eslint-config devDeps not accessible, moving to deps

- examples/client-example/package.json
- packages/client/package.json
- packages/react-core/package.json
- packages/react-core/setupTest.ts
- packages/react-core/test/core/KnockProvider.test.tsx
- packages/react-core/test/core/utils.test.ts
- packages/react-core/test/feed/KnockFeedProvider.test.tsx
- packages/react-core/vite.config.ts
- packages/react-native/package.json
- packages/react-native/vite.config.ts
- packages/react/package.json
- packages/react/setupTest.ts
- packages/react/test/feed/Button.test.tsx
- packages/react/test/feed/EmptyFeed.test.tsx
- packages/react/test/test-utils.tsx
- packages/react/vite.config.ts
- yarn.lock
Sets up Vitest and testing-library for react and react-core with a few base test cases. 
Holding off on react native as Vitest doesn't support it. There are some workarounds we could consider like rendering using react-native-web during testing or using Jest. https://github.com/vitest-dev/vitest/issues/1321
> chore: add testing set up and base coverage for React SDKs

- .changeset/young-rules-thank.md
- packages/client/package.json
- packages/client/src/clients/feed/interfaces.ts
- packages/client/src/clients/feed/types.ts
- packages/client/src/clients/preferences/index.ts
- packages/client/src/clients/preferences/interfaces.ts
- packages/client/src/interfaces.ts
- packages/client/src/knock.ts
- packages/types/.eslintrc.js
- packages/types/README.md
- packages/types/package.json
- packages/types/src/common.d.ts
- packages/types/src/index.d.ts
- packages/types/src/index.ts
- packages/types/tsconfig.json
- packages/types/tsup.config.ts
- yarn.lock
Adds a `@knocklabs/types` package with a few shared types. Open to feedback on what other types we want to include there. Looking through the other packages, most of the types are pretty specific to each package, so it depends on where we want to draw the line of what gets put in types and what stays local to each package.
> feat: add shared types package

- examples/slack-connect-example/lib/api.ts
- packages/client/src/knock.ts
- packages/react/src/modules/slack/components/ConnectToSlackButton/ConnectToSlackButton.tsx
- packages/react/src/modules/slack/hooks/useManageSlackConnection.ts
- packages/react/src/modules/slack/hooks/useSlackChannels.ts
Adds a pop up window for the slack auth flow rather than using a redirect for this. Relies on switchboard PR to return the window close html: https://github.com/knocklabs/switchboard/pull/1909
> feat(kno-5138): enable popup window for slack auth flow

- packages/react-core/src/modules/slack/hooks/useConnectedSlackChannels.ts
- packages/react/src/modules/slack/components/SlackChannelCombobox/AddConnectedSlackChannelInput.tsx
- packages/react/src/modules/slack/components/SlackChannelCombobox/ConnectionErrorInfoBoxes.tsx
- packages/react/src/modules/slack/components/SlackChannelCombobox/SlackChannelCombobox.tsx
- packages/react/src/modules/slack/components/SlackChannelCombobox/styles.css
This is a v1 text input for adding channels that I'd like to get in for us to play with and see what it needs. 
Basically we want to restrict using the combobox to only work if you have fewer than 1000 slack channels. if you have more than that, we'll intentionally degrade the experience to help with performance, which is where we have this input box come in.
It's very stupid, it just takes a text string and posts it to the setChannelData endpoint as an entry in channel data. It does not check if it belongs to a real slack channel (and it shouldn't this is out of scope). It does check if the channel id already exists in the connected channel ids. Once it's in, we can tweak the design.
https://www.loom.com/share/7fda538f23fc4fd789bd837f2eb3cc44
> feat(kno-5241): if max channels reached, use text input to add channel

- examples/nextjs-example/hooks/useLocalStorage.tsx
- examples/nextjs-example/pages/api/identify.ts
- examples/nextjs-example/pages/index.tsx
- packages/client/src/api.ts
- packages/client/src/clients/feed/feed.ts
- packages/client/src/clients/feed/index.ts
- packages/client/src/clients/feed/store.ts
- packages/client/src/clients/feed/types.ts
- packages/client/src/interfaces.ts
- packages/client/src/knock.ts
- packages/react-core/src/modules/core/context/KnockProvider.tsx
- packages/react-core/src/modules/core/hooks/useAuthenticatedKnockClient.ts
- packages/react-core/src/modules/feed/context/KnockFeedProvider.tsx
- packages/react-core/src/modules/feed/hooks/useNotifications.ts
This is quite a few updates, but it essentially boils down to:
- Gracefully handling userId and userToken changes by reauthenticating and reconnecting real-time connections
- Memoizing options to prevent the API client from being recreated when unnecessary
- Removing `store.destroy()` when tearing down a feed instance which was causing the state management to get disconnected
> fix: gracefully handle credential changes

- package.json
The release process was utilizing `changeset publish` which isn't compatible with yarn workspaces. 
See notes:
Changeset runs npm publish under the hood, can see here: https://github.com/changesets/changesets/blob/418551020e9ff409878ca2c06944f03098d0f126/packages/cli/src/commands/publish/npm-utils.ts#L191
Which would run this: https://yarnpkg.com/cli/npm/publish
This cli command isn't aware of workspaces. So to publish with workspaces context you need to run yarn workspaces foreach . This command goes into each workspace (with the context of the other workspaces), so if you run yarn npm publish within that command then yarn can successfully swap workspace:^ for the correct version number. Contrary to what changeset does which is cd into the package folder and runs yarn npm publish.
> fix: Add correct release script to pkg json

- packages/react/src/modules/slack/components/SlackChannelCombobox/SlackChannelCombobox.tsx
- packages/react/src/modules/slack/components/SlackChannelCombobox/SlackChannelOption.tsx
- packages/react/src/modules/slack/components/SlackChannelCombobox/icons/CheckmarkIcon.tsx
- packages/react/src/modules/slack/components/SlackChannelCombobox/styles.css
This handles the case where a user has a slack channel connected in Knock, but it isn't found in the list of Slack channels from the API, potentially because the bot doesn't have access to it (like a private channel it doesn't belong to). In this case it also wouldn't be able to post to the channel so it is accurate to show to the user that it is not connected.
It also updates some minor styling issues.
> fix(kno-5254): hide inaccessible channels

- .changeset/tame-plants-know.md
- packages/client/package.json
- packages/client/src/clients/feed/feed.ts
- packages/client/vite.config.ts
- packages/react-core/package.json
- packages/react-core/vite.config.ts
- packages/react/package.json
- packages/react/vite.config.ts
Customers were having issues with the latest builds of our packages. This was because they were trying to resolve `.es.js` files as modules which the JS compiler doesn't know how to interpret. The correct file extension for modules is `.mjs` so this PR modifies the vite config to accomplish this.
See this similar issue for more info: https://github.com/FortAwesome/Font-Awesome/issues/16439
> fix: esm issues round 2

- .editorconfig
- examples/client-example/src/App.js
- packages/client/src/clients/feed/feed.ts
This PR adds a second event broadcast on FeedItem status updates in the correct format, e.g. `items.archived`. It also add functionality to the client example to test this new event, which works as expected:
For some reason, the diff make the spacing look funky, but everything looks good if you look at the actual code.
> fix: update event format for client status updates

- .changeset/poor-otters-whisper.md
- packages/react/src/modules/slack/components/SlackChannelCombobox/styles.css
Makes the list box opaque so that it covers any elements underneath it.
> fix(kno-5450): make slack combobox list box opaque

- .changeset/gorgeous-shirts-camp.md
- packages/react-core/src/modules/slack/hooks/useSlackConnectionStatus.ts
If the API returns `connection: {ok: false}` it should just show disconnected instead of an error. This relates to this Switchboard change where we're explicitly returning this: https://github.com/knocklabs/switchboard/pull/2077
> fix(kno-5521): handle connection: false error

- examples/nextjs-example/components/SendNotificationForm.tsx
- examples/nextjs-example/pages/api/notify.ts
- packages/client/src/clients/feed/interfaces.ts
- packages/react/src/modules/feed/components/NotificationCell/NotificationCell.tsx
- packages/react/src/modules/feed/components/NotificationCell/styles.css
- packages/react/src/modules/feed/components/NotificationFeed/NotificationFeed.tsx
- packages/react/src/modules/feed/components/NotificationFeedPopover/NotificationFeedPopover.tsx
- Adds support for rendering `actions` as buttons in the notification cell
- Adds `onNotificationButtonClick` and `onButtonClick` handlers
- Adds support for sending different template types in the example app
> feat: support in-app actions in `NotificationCell`

- .changeset/lucky-trainers-draw.md
- packages/client/src/clients/users/index.ts
Not sure how we ever missed having these in the client JS given that they are supported?
> feat: add user get and identify methods

- .changeset/forty-bears-jog.md
- examples/nextjs-example/package.json
- packages/client/src/clients/slack/index.ts
- packages/client/src/clients/slack/interfaces.ts
- packages/react-core/package.json
- packages/react-core/src/modules/slack/context/KnockSlackProvider.tsx
- packages/react-core/src/modules/slack/hooks/useSlackChannels.ts
- packages/react/package.json
- yarn.lock
* Ditches `@tankstack/react-query` for `swr` which supports React 16.11+
* Removes the dependencies and use of `react-query`
* Fixes the react peerDep version in our package.json files
> fix: swap usequery with swr for react 16 support

- .changeset/warm-cooks-work.md
- packages/react-core/package.json
- packages/react-core/vite.config.ts
- packages/react/package.json
- packages/react/vite.config.ts
- yarn.lock
When using React < 18 users will run into this error: 
```
Module not found: Error: Can't resolve 'react/jsx-runtime' in '[FILE]'
Did you mean 'jsx-runtime.js'?
BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```
The issue is described in this thread: https://github.com/facebook/react/issues/20235
The fix was implemented in React 18, but the only "fixes" that exist if we're using the JSX runtime are to patch webpack configs, which is not …
> fix: use jsx classic runtime to avoid issues on react < 18

- .changeset/brown-deers-cough.md
- packages/react-native/src/modules/feed/components/NotificationFeedContainer/NotificationFeedContainer.tsx
- packages/react/src/modules/core/components/Button/ButtonGroup.tsx
- packages/react/src/modules/feed/components/NotificationFeedContainer/NotificationFeedContainer.tsx
react 16 type don't let you use `PropsWithChildren` with empty
> fix: don't use propswithchildren w/o props

- .changeset/four-icons-provide.md
- packages/client/src/clients/feed/feed.ts
- packages/client/src/clients/feed/interfaces.ts
- packages/client/src/clients/feed/types.ts
* feed events should all be `items.${type}` as well as `items:${type}`
* make some generic types interfaces
* allow `FeedEventPayload` to accept a generic
> fix: feed events should all be items. and fixed types

- .changeset/healthy-lemons-begin.md
- packages/client/src/clients/feed/feed.ts
With `auto_manage_socket_connection` on, we disconnect and reconnect websockets for idle tabs. This is detected with the `visibilitychange` event listener which gets added when the feed instance is created or reinitialized. The event listener is cleaned up when the feed instance is torn down. 
There was an issue where we were also adding the listener in `handleVisibilityChange` when we reinitialize the realtime connection when the tab becomes active again (`document.visibilityState === "visible"`). This PR adds a flag so we can check if the listener was already added and early returns if it has been so we don't accidentally keep re-adding the event listener. 
You can test this by :
1. running the Nextjs example and enabling `auto_manage_socket_connection`
1. open the demo app in multiple …
> fix: check if visibilitychange listener is present before adding

- .changeset/nervous-lizards-press.md
- packages/react-core/src/modules/feed/hooks/useNotifications.ts
In react strict mode, updates from `useNotifications` was not persisted downstream, so the UI seemed unresponsive as it wasn't getting updates. There is likely an underlying issue that we need to investigate further, but using zustand's [transient updates](https://github.com/pmndrs/zustand?tab=readme-ov-file#transient-updates-for-often-occurring-state-changes) pattern seems to work for both react strict mode and a production build.
> fix: subscribe to state updates for notifications

- .changeset/four-actors-itch.md
- packages/react-core/src/modules/core/context/KnockProvider.tsx
- packages/react-core/src/modules/core/hooks/useAuthenticatedKnockClient.ts
- packages/react-core/test/core/useAuthenticatedKnockClient.test.ts
- Uses a shallow comparison and a memo for `options` passed into the `useAuthenticatedKnockClient` hook to ensure the options are stable between re-renders
- Adds a test for the hook (!)
> fix: ensure that options are stable between re-renders for useAuthenticatedKnockClient

- .changeset/empty-taxis-nail.md
- packages/client/src/clients/feed/feed.ts
Destroying the store unbinds listeners, which breaks our workaround for handling double renders in React strict mode. There's definitely something deeper going on here, but I cannot for the life of me figure it out.
> fix: render issues in next 14 with react 18 strict mode

- .changeset/rich-foxes-tease.md
- packages/react/src/modules/core/hooks/useComponentVisible.ts
A customer was experiencing an issue where when the notification feed popover was open, clicking a link outside of the popover would cause the page to hard refresh when using `react-router-dom`. Removing `event.stopPropogation()` from the `useComponentVisible` hook fixed this issue. 
[KNO-6065](https://linear.app/knock/issue/KNO-6065/[js-sdk]-investigate-event-propagation-issue-with-react-popover)
> fix: remove event stop propogation from outside click hook

- .changeset/kind-yaks-compete.md
- packages/client/src/clients/feed/store.ts
As of version 0.8.21, the CJS feed client breaks which can be reproduced by a new Ember JS project with the error
```
TypeError: i is not a function
at Module.p [as default] (store.js:1:654)
at new v (feed.js:1:1035)
at f.initialize (index.js:1:550)
```
This can be resolved by accessing `require("zustand/vanilla").default` in the CJS build. This seems to be caused by an issue with Zustand v3 not having the correct exports for sub packages (e.g. it breaks for `zustand/vanilla`). Checking the type of the default zustand export seems to fix this issue.
Tested locally against an Ember project and against our Nextjs and Client examples to make sure this doesn't cause any regressions.
> fix: check type of zustand create and fallback to .default

- .changeset/perfect-chairs-impress.md
- packages/react/src/modules/feed/components/NotificationCell/styles.css
Long, unbroken text (like links) caused the notification cell to overflow horizontally. This PR updates the word-break to `break-word` to fix that.
> fix: wrap long, unbroken text in notification cell

- .changeset/twelve-dogs-hide.md
- packages/react-native/src/modules/push/KnockExpoPushNotificationProvider.tsx
Adding a prop to our KnockExpoPushNotificationProvider to allow users to opt out of our auto registration
> fix: RN push provider flag

- examples/in-app-message-example/src/App.tsx
- packages/client/src/clients/in-app-messages/channel-client.ts
- packages/client/src/clients/in-app-messages/message-client.ts
- packages/react-core/src/modules/in-app-message/hooks/useInAppMessages.ts
- Makes options stable which makes the message client created by `useInAppMessage(s)` stable
- Adds logs to message and channel client to debug client creation
Example shows 1 channel client created with 3 message clients created which is expected for:
- Default banner
- Custom banner
- Default modal
- None for card as the demo uses the view card component
> fix: make message client stable

- .changeset/strange-elephants-know.md
- examples/react-native-example/.env.sample
- examples/react-native-example/.gitignore
- examples/react-native-example/App.tsx
- examples/react-native-example/FCMPushNotificationHandler.tsx
- examples/react-native-example/PushHandler.tsx
- examples/react-native-example/README.md
- examples/react-native-example/android/app/build.gradle
- examples/react-native-example/android/build.gradle
- examples/react-native-example/firebase.json
- examples/react-native-example/index.js
- examples/react-native-example/package.json
- examples/react-native-example/react-native-config.d.ts
- yarn.lock
This PR updates the vanilla React Native example app to demonstrate registering for Firebase Cloud Messaging (FCM) push notifications using Knock and [React Native Firebase](https://rnfirebase.io/).
Full disclosure: I only tested this on Android. 🙃
> feat(kno-7176): add FCM push example to React Native sample app

- .github/workflows/prerelease.yml
Adds a prerelease action which runs the changeset action in prerelease mode. Defaults to running against the `next` branch and appending `rc` to the versions
Changesets prerelease docs: https://github.com/changesets/changesets/blob/main/docs/prereleases.md
> feat: add prerelease action

- .changeset/curly-pets-guess.md
- examples/react-native-example/FCMPushNotificationHandler.tsx
Small fix. Turns out [`onTokenRefresh`](https://github.com/invertase/react-native-firebase/blob/9c940857a3759f85fad2f8d995b83f7c08058d6b/packages/messaging/lib/index.d.ts#L790) returns an unsubscribe function.
> fix(kno-7176): unsubscribe onTokenRefresh listener in React Native sample app

- .changeset/red-spiders-promise.md
- packages/client/src/api.ts
Ensure axios is always imported correctly in the client package.
Modified the `ApiClient` class in `packages/client/src/api.ts` to handle cases where the axios export is not the default in certain bundlers (e.g., Webpack). This change addresses an issue reported in the axios repository.
1. Build the client package using different bundlers, especially Webpack.
2. Verify that the axios instance is created correctly without any import-related errors.
3. Ensure that API calls using the client still function as expected.
This change resolves a potential issue where the axios library might not be imported correctly in certain bundling scenarios. By accounting for both default and non-default exports, we ensure consistent behavior across different build environments, improving the reliability …
> fix: if axios is not imported as the default, then account for it

- packages/client/src/clients/in-app-messages/message-client.ts
- packages/client/src/clients/in-app-messages/types.ts
- packages/client/src/clients/users/interfaces.ts
The API allows filtering by trigger_data, but expects it to be a string. An object is easier to work with and matches the feeds API, so we're going to just convert the object to a string before calling the API.
> fix: convert trigger_data to string for in-app-messages api

- packages/react-core/package.json
- packages/react-core/src/modules/core/hooks/useStableOptions.ts
- packages/react-core/src/modules/in-app-messages/hooks/useInAppMessages.ts
- yarn.lock
Fixes this issue: https://knocklabs.slack.com/archives/C079G6X3DD4/p1731085160770939
* Need to re-run the effect upon getting new options, so adding inAppMessagesClient to the useEffect deps array in the in-app message client
* Uses `fast-deep-equal` instead of `zustand/shallow` since the latter does not handle array values, and some of our query params can be arrays.
> fix: refetch in-app messages when query options change 

- .changeset/silly-balloons-thank.md
- .github/dependabot.yml
- packages/react/package.json
- yarn.lock
A customer is experiencing an issue whereby their React 16 app fails to build when our React SDK is present, due to the following error:
```
Uncaught Error: Cannot find module 'react/jsx-runtime'
```
The stacktrace the customer provided indicates `react/jsx-runtime` is being imported by our Radix Primitives dependencies. Even though #115 updated _our own_ packages to support React 16, we can’t control the JSX transform being used by the dependencies we pull in.
From what I can tell, Radix Primitives v1.1.0 was the first version in which they began using [React’s “new” JSX transform](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html), so pinning the Radix dependencies in our codebase to an earlier version should (hopefully) fix this.
My plan is to cut a …
> chore(kno-7236): pin Radix dependencies to support React 16

- packages/client/src/clients/in-app-messages/types.ts
Dependent on https://github.com/knocklabs/switchboard/pull/3239.
Adds a `schema_version` param to the in-app messages query options.
[KNO-7459](https://linear.app/knock/issue/KNO-7459/[sdk]-add-version-pinning-support-to-in-app-messages-client)
> feat: add schema_version to in app messages query options

- .changeset/fair-masks-whisper.md
- packages/client/src/api.ts
- packages/client/vite.config.mts
#261 fixed an issue whereby Axios was imported incorrectly in the CJS bundle of our `client` package. We just learned that the same issue applies to `axios-retry`. [axios-retry’s README](https://github.com/softonic/axios-retry/blob/4c38b77bce745f6d077a55c5ac02aafe9be72dc1/README.md?plain=1#L16-L17) even indicates that CJS builds should import it using `require('axios-retry').default` rather than `require('axios-retry')`.
Rather than apply the same workaround to `axios-retry`, I’m pretty certain we can instead leverage [Rollup’s `output.interop` option](https://rollupjs.org/configuration-options/#output-interop) and set it to `"compat"`. This will make it so that Rollup automatically checks for a `default` property on imported modules. We already use the `"compat"` interop mode in our …
> fix: bundle client package using "compat" interop

- .changeset/poor-colts-work.md
- packages/client/src/clients/messages/interfaces.ts
This PR updates the `BulkUpdateMessagesInChannelProperties` type to include the missing `"archived"`, `"unarchived"`, `"interacted"`, and `"link_clicked"` values for `engagement_status`.
> fix(KNO-7439): engagement_status in BulkUpdateMessagesInChannelProperties type

- packages/react/src/modules/in-app-messages/components/Banner/Banner.tsx
- packages/react/src/modules/in-app-messages/components/Banner/styles.css
- packages/react/src/modules/in-app-messages/components/Card/Card.tsx
- packages/react/src/modules/in-app-messages/components/Card/styles.css
- packages/react/src/modules/in-app-messages/components/Modal/Modal.tsx
- packages/react/src/modules/in-app-messages/components/Modal/styles.css
Following the update that converted the body fields of OOTB message types to markdown (https://github.com/knocklabs/control/pull/4362), this PR now renders the rendered body/html content as an inner html in the components. This should handle the rendered content whether it was a text or markdown field.
[KNO-7559](https://linear.app/knock/issue/KNO-7559/[sdk]-change-ootb-message-type-body-fields-to-markdown)
> chore: render body in ootb components as inner html

- .changeset/healthy-ladybugs-drum.md
- examples/nextjs-example/next-env.d.ts
- examples/nextjs-example/pages/api/identify.ts
- examples/nextjs-example/pages/api/notify.ts
- examples/nextjs-example/pages/index.tsx
- packages/client/src/clients/feed/feed.ts
- packages/client/src/knock.ts
Currently, we require that a `userId` must be set in order to initialize Knock. This means that our customers have to wrap their `KnockProvider` in conditional logic if the user they're authenticating is not available at render.
We previously made the entire client library resilient to userId and userToken changes; gracefully reconnecting and reinitializing when that happens.
This PR changes the behavior of the Feed instance so that when unauthenticated no feed calls or socket connections are initialized. This makes it so that `undefined` can be passed the `userId` and feed clients can be initialized without any fetches, and therefore errors, occurring on the client.
I also took a moment here to fix the logic with badge counts where bulk archiving items could lead to negative badge …
> fix: allow falsey userIds for auth and gracefully handle

- .changeset/fair-masks-whisper.md
- .changeset/tall-scissors-reflect.md
- packages/client/src/api.ts
- packages/client/vite.config.mts
This PR cherry-picks commit bc99374, which updates the Client SDK with the same changes applied to the `main` branch by #315.
> fix(KNO-7520): bundle client package using "compat" interop

- .changeset/tall-rocks-help.md
- packages/client/src/clients/ms-teams/index.ts
- packages/client/src/clients/ms-teams/interfaces.ts
- packages/client/src/index.ts
This PR updates `MsTeamsClient` with two new functions, `getTeams` and `getChannels`, for use with TeamsKit. These functions make network requests to upcoming API endpoints.
> feat(KNO-7619): add getTeams and getChannels to MsTeamsClient

- .changeset/shy-impalas-wave.md
- packages/client/src/clients/ms-teams/interfaces.ts
- packages/react-core/src/index.ts
- packages/react-core/src/interfaces.ts
- packages/react-core/src/modules/i18n/languages/en.ts
- packages/react-core/src/modules/i18n/languages/index.ts
- packages/react-core/src/modules/ms-teams/hooks/index.ts
- packages/react-core/src/modules/ms-teams/hooks/useConnectedMsTeamsChannels.ts
- packages/react-core/src/modules/ms-teams/hooks/useMsTeamsChannels.ts
- packages/react-core/src/modules/ms-teams/hooks/useMsTeamsTeams.ts
- packages/react-core/src/modules/ms-teams/index.ts
- packages/react-core/src/modules/ms-teams/interfaces.ts
- packages/react-core/src/modules/slack/hooks/useConnectedSlackChannels.ts
- packages/react-core/src/modules/slack/interfaces.ts
- packages/react/src/modules/slack/components/SlackChannelCombobox/SlackChannelCombobox.tsx
This PR adds three new hooks for use in TeamsKit:
- `useMsTeamsTeams`, which loads a list of teams for a tenant.
- `useMsTeamsChannels`, which loads a list of channels within a given team.
- `useConnectedMsTeamsChannels`, which returns the connections channel data for a recipient object, and allows updating the channel data.
These hooks are based on the existing SlackKit hooks `useSlackChannels` and `useConnectedSlackChannels`.
Here’s a quick Loom demonstrating these hooks:
https://www.loom.com/share/cd6ead2a92654dbca7ac3e3e6550505e?sid=d7fb9469-1828-4862-a62a-d022c29c5a2f
> feat(KNO-7622): add TeamsKit hooks for teams and channels

- .changeset/dirty-parents-add.md
- .changeset/polite-dodos-itch.md
- packages/react-core/src/modules/slack/hooks/useConnectedSlackChannels.ts
- packages/react/src/modules/slack/components/SlackChannelCombobox/SlackChannelCombobox.tsx
This PR updates the `useConnectedSlackChannels` hook so that it uses [SWR](https://swr.vercel.app/) under the hood. This allows us to optimistically update the returned array of connections when `updateConnectedChannels` is called.
We can also update `SlackChannelCombobox` to eliminate a `useState` hook that in effect implemented optimistic updates of the UI whenever `updateConnectedChannels` was called. There should be no change in the behavior of this component.
https://github.com/user-attachments/assets/f6b5c5e8-c9dc-48b8-8610-96bc1f453b46
https://github.com/user-attachments/assets/333573b8-14a1-412e-b746-82a6d63287cc
> feat(KNO-7785): use SWR in useConnectedSlackChannels hook

- .changeset/red-drinks-brake.md
- packages/client/src/clients/preferences/index.ts
- packages/client/src/clients/users/index.ts
- packages/client/src/knock.ts
Added authentication checks across user and preference-related operations to prevent access when uninitialized (e.g. userId is null or undefined).
- Added a new `failIfNotAuthenticated` method to validate authentication status
- Implemented authentication checks before executing user-related operations
- Added validation before performing preference-related actions
- Each API endpoint now verifies authentication status before proceeding
> fix: fail if not authenticated on core user methods

- .changeset/blue-tigers-hunt.md
- packages/react/.eslintrc.js
- packages/react/package.json
- packages/react/src/modules/feed/components/NotificationCell/Avatar.tsx
- packages/react/src/modules/feed/components/NotificationCell/NotificationCell.tsx
- packages/react/src/modules/feed/components/NotificationIconButton/NotificationIconButton.tsx
- packages/react/src/modules/ms-teams/components/MsTeamsChannelCombobox/MsTeamsChannelCombobox.tsx
- yarn.lock
This PR:
- Installs [eslint-plugin-jsx-a11y](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y) and updates our ESLint config to extend eslint-plugin-jsx-a11y’s strict configuration.
- Fixes the few existing violations caught by eslint-plugin-jsx-a11y.
> chore(KNO-7803): lint React SDK using eslint-plugin-jsx-a11y

- .changeset/three-ears-learn.md
- packages/client/src/clients/feed/interfaces.ts
- packages/client/src/clients/messages/interfaces.ts
1### TL;DR
Added new timestamp fields for tracking user engagement with feed items and messages.
Added three new timestamp fields to both `FeedItem` and `Message` interfaces:
- `clicked_at`: Tracks when the item/message was clicked
- `interacted_at`: Tracks when any interaction occurred
- `link_clicked_at`: Tracks when embedded links were clicked
1. Verify that feed items and messages include the new timestamp fields in their responses
2. Confirm that these fields are properly populated when:
- Clicking on an item/message
- Interacting with content
- Clicking embedded links
3. Validate that null values are returned when no interactions have occurred
To provide more granular tracking of user engagement with content, enabling better analytics and user behavior insights. This data can be …
> fix: include all message and feed item fields on types

- .changeset/lovely-plums-relax.md
- packages/react/package.json
- packages/react/src/modules/ms-teams/components/MsTeamsChannelCombobox/MsTeamsChannelInTeamCombobox.tsx
- packages/react/src/modules/ms-teams/components/MsTeamsChannelCombobox/MsTeamsTeamCombobox.tsx
- packages/react/src/modules/ms-teams/components/MsTeamsChannelCombobox/styles.css
- packages/react/src/modules/ms-teams/utils.ts
- yarn.lock
This PR updates the Telegraph dependencies used by the React SDK to the latest versions. This includes changes to the `MsTeamsTeamCombobox` and `MsTeamsChannelInTeamCombobox` components (both of which are rendered by `MsTeamsChannelCombobox`) so that they no longer use Telegraph’s legacy combobox behavior.
> chore(KNO-7799): update Telegraph dependencies

- .changeset/happy-jars-tap.md
- packages/react/package.json
- packages/react/src/modules/ms-teams/components/MsTeamsChannelCombobox/MsTeamsChannelInTeamCombobox.tsx
- packages/react/src/modules/ms-teams/components/MsTeamsChannelCombobox/MsTeamsTeamCombobox.tsx
- packages/react/src/modules/ms-teams/components/MsTeamsChannelCombobox/styles.css
- yarn.lock
This PR:
- Updates the Telegraph dependencies used by the React SDK to the latest versions
- Removes some custom CSS styles that were required prior to knocklabs/telegraph#393 and knocklabs/telegraph#396.
> chore(KNO-7837): update Telegraph dependencies

- .changeset/serious-carrots-itch.md
- .changeset/sweet-dancers-behave.md
- examples/ms-teams-connect-example/pages/_app.tsx
- examples/ms-teams-connect-example/pages/styles.css
- examples/slack-connect-example/pages/_app.tsx
- examples/slack-connect-example/pages/styles.css
- packages/react/src/modules/ms-teams/components/MsTeamsChannelCombobox/MsTeamsChannelInTeamCombobox.tsx
- packages/react/src/modules/ms-teams/components/MsTeamsChannelCombobox/MsTeamsTeamCombobox.tsx
- packages/react/src/modules/slack/components/SlackChannelCombobox/SlackChannelCombobox.tsx
This PR fixes a bug whereby the page layout could shift whenever a combobox opens and the `<body>` element has non-zero padding.
When the combobox opens, a style `body[data-scroll-locked]` is applied by `react-remove-scroll-bar` (which is a dependency of `react-remove-scroll`, used by Radix):
By default, `react-remove-scroll-bar` uses [a “gap mode” of `"margin"`](https://github.com/theKashey/react-remove-scroll-bar/blob/29e9fcd1eecf7d3b77a767941c4a57fe461fc1e4/src/utils.ts#L29). This means it uses [the margin attributes rather than padding](https://github.com/theKashey/react-remove-scroll-bar/blob/29e9fcd1eecf7d3b77a767941c4a57fe461fc1e4/src/utils.ts#L22-L24) when computing this `body[data-scroll-locked]` style.
There’s a lot of discussion in the Radix repo about page layouts shifting due …
> fix(KNO-7854): fix page layout shifting when combobox opens

- .github/dependabot.yml
[Just as we do in the control repo](https://github.com/knocklabs/control/blob/71266d417e6821c7b84c99afc1eea514bbd574a6/.github/dependabot.yml#L24-L27), we should update Telegraph dependencies in a single PR.
> chore(KNO-7863): group Telegraph dependencies in Dependabot config

- packages/expo/src/modules/push/KnockExpoPushNotificationProvider.tsx
The `useEffect` that controls the registering does not include `autoRegister` as a dependency, preventing the registration from firing when `autoRegister` changed. 
Merging into the React 19 branch to get it out with the next release.
Addresses #430 
[Linear KNO-7971](https://linear.app/knock/issue/KNO-7971/knockexpopushnotificationprovider-autoregister-prop-isnt-reactive-not)
> fix(KNO-7971): fixes autoregister dependency in KnockExpoPushNotificationProvider useEffect

- examples/nextjs-example/pages/custom.tsx
- packages/react-core/src/modules/feed/hooks/index.ts
- packages/react-core/src/modules/feed/hooks/useNotificationStore.ts
- packages/react-core/test/feed/useNotificationStore.test.tsx
[Customers were running into issues using the new release candidate.](https://knocklabs.slack.com/archives/C085BK3QYSX/p1741195268891259) This attempts to align the functionality and typing to its original behavior.
The types are a little sketchy but I could not get it to behave the way I wanted it to without type casting. If you have suggestions please let me know!
I tested this in our `client` and `nextjs-example` repos, both with and without a selector. It appears to function great and produce accurate types.
[Here is the current `useNotificationStore` code in main for reference](https://github.com/knocklabs/javascript/blob/main/packages/react-core/src/modules/feed/hooks/useNotificationStore.ts)
Also added a new page in our nextjs example that mimics [the guide from our …
> fix(kno-7523): fixes bad returns from useNotificationStore

- .changeset/dull-carrots-juggle.md
- packages/react-core/src/modules/ms-teams/hooks/useMsTeamsTeams.ts
- packages/react-core/src/modules/slack/hooks/useSlackChannels.ts
This PR fixes an issue with the two hooks in our React SDK that use `useSWRInfinite` internally, `useMsTeamsTeams` and `useSlackChannels`.
Both of these hooks call `setSize` within a `useEffect` so that they continuously load pages of data until the max number of teams (or channels) has been loaded, or there are no more pages available:
https://github.com/knocklabs/javascript/blob/7d68b259200bf828198bc2002bd255812d41ce12/packages/react-core/src/modules/ms-teams/hooks/useMsTeamsTeams.ts#L90-L92
Calling `setSize` to fetch the next page seems to trigger SWR’s revalidation behavior. Because [`useSWRInfinite`’s `revalidateFirstPage` option](https://swr.vercel.app/docs/pagination#parameters) is `true` by default, this means the first page is refetched every time we call `setSize`.
To fix this, …
> fix(KNO-8072): set revalidateFirstPage option of useSWRInfinite to false

- .changeset/better-bugs-sneeze.md
- examples/client-example/vite.config.js
- examples/nextjs-example/next-env.d.ts
- examples/slack-connect-example/next-env.d.ts
- packages/client/src/clients/feed/feed.ts
- packages/client/src/clients/feed/interfaces.ts
This adds support for filtering messages by a given date range.
It also removes `optimizeDeps` from the client example app which caused the dependency to be cached.
> feat(8086): add support for date range filters in the feed

- .changeset/good-baths-search.md
- examples/client-example/src/App.jsx
- packages/client/src/clients/feed/feed.ts
- packages/client/src/clients/feed/utils.ts
- packages/client/test/feed.test.ts
Previously, we weren't respecting the date range option upon feed initialization. This moves the transformation helper into utils so that we can use it when the feed is initialized and when it fetches.
We're doing this transformation because while the date range helper uses `inserted_at_date_range` with start and end times, the Switchboard api expects `inserted_at.gt` etc.
> fix(kno-8221): date range option can be passed to initialize feed

- .changeset/silver-roses-relate.md
- examples/expo-example/src/NotificationFeedContainer.tsx
- packages/react-native/src/modules/feed/components/NotificationFeedComponents/NotificationFeed.tsx
This will allow styling the outermost `<View>` rendered by the `<NotificationFeed>` component.
> feat(KNO-8294): add containerStyle prop to React Native NotificationFeed component

- .changeset/bright-moose-listen.md
- examples/slack-connect-example/pages/index.tsx
This PR updates the SlackKit example app so that rendered `<SlackAuthButton>` components request the scopes required for use with [email-based user ID resolution](https://docs.knock.app/integrations/chat/slack/sending-a-direct-message#enabling-email-based-user-id-resolution).
> chore(KNO-8352): update SlackKit example app scopes

- .changeset/fancy-radios-beg.md
- packages/react-native/src/assets/BellIcon.tsx
- packages/react-native/src/modules/feed/components/NotificationIconButton/NotificationIconButton.tsx
This PR adds another style override to the `BellIcon` component so that you can set its stroke width
> feat(KNO-8430): make bell icon stroke width configurable

- .changeset/great-fans-post.md
- packages/react-core/src/modules/feed/hooks/useNotifications.ts
Refactors `useNotifications` to use `useEffect` instead of `useMemo` for initializing the Knock feed client. Previously, `useMemo` was used to set up the feed and call `dispose()` when dependencies changed. However, `useMemo` is not designed for side effects or cleanup—it simply memoizes a return value and does not run cleanup logic on component unmount. This meant that the feed client would not be disposed when the component unmounted, potentially leading to memory leaks or lingering subscriptions. By switching to `useEffect`, we ensure that the feed client is properly initialized and disposed of both when dependencies change and when the component unmounts, resulting in more predictable and stable behavior.
[KNO-8435](https://linear.app/knock/issue/KNO-8435/[sdk]-investigate-potential-me …
> fix: useNotifications memory leak

- .changeset/rich-rivers-hide.md
- packages/client/src/clients/feed/feed.ts
- packages/client/src/helpers.ts
- packages/client/src/knock.ts
- packages/react-core/src/modules/core/context/KnockProvider.tsx
- packages/react-core/src/modules/feed/context/KnockFeedProvider.tsx
- packages/react-core/src/modules/feed/hooks/useNotifications.ts
- packages/react/src/modules/feed/components/NotificationFeedPopover/NotificationFeedPopover.tsx
- revert the memory leak fix from #495 
- fix typescript issue with `buttonRef`
- fix typescript issue with api key and feed id
- add check that feedId is a UUID in the feed constructor
> fix: quality of life improvements

- .changeset/fancy-bats-spend.md
Forgot to include a changeset in [the previous PR](https://github.com/knocklabs/javascript/pull/503) to release new versions.
> chore: changeset to release new versions (guide activation location rules)

- .changeset/salty-lies-battle.md
- .github/dependabot.yml
- packages/client/package.json
- yarn.lock
[v4 of nanoid dropped support for CJS](https://github.com/ai/nanoid/blob/main/CHANGELOG.md#40), so this PR downgrades the client SDK’s nanoid dependency to the latest v3 release so that we restore support for CJS.
> fix(KNO-8590): fix CJS builds by downgrading nanoid

- .changeset/tricky-houses-swim.md
- .github/dependabot.yml
- packages/client/package.json
- packages/react-core/package.json
- yarn.lock
This PR downgrades the `@tanstack/store` package to v0.6.0 (and `@tanstack/react-store` to v0.6.1) in order to fix the [type error](https://github.com/knocklabs/control/actions/runs/14764163532/job/41451741651?pr=4994) we are seeing in [the dependabot PR](https://github.com/knocklabs/control/pull/5033) to upgrade our `@knocklabs/react` package to the latest. It's further discussed in this slack thread:  https://knocklabs.slack.com/archives/C06A1FCF9L3/p1746214176542269.
To summarize what's going on:
* In #480, we upgraded the `@tanstack/store` and `@tanstack/react-store` deps to the latest v0.7.0 in order to support React 19 in our SDKs (React 19 was added as a peer dep in `@tanstack/react-store` at v0.6.1)
* It appears the `@tanstack/store` latest version v0.7.0 has a minimum typescript …
> fix: bump down tanstack store packages to 0.6.x

- .changeset/mighty-keys-slide.md
- packages/react-native/package.json
- packages/react-native/src/index.ts
- yarn.lock
This PR fixes feed initialization in our React Native and Expo SDKs by installing [react-native-get-random-values](https://github.com/LinusU/react-native-get-random-values). Nano ID requires this dependency when it’s used with React Native and Expo. See [this note in Nano ID’s README](https://github.com/ai/nanoid#react-native).
Before installing this dependency, the following error would occur:
```
(NOBRIDGE) ERROR  ReferenceError: Property 'crypto' doesn't exist
This error is located at:
in KnockFeedProvider (at App.tsx:29)
in InternalKnockExpoPushNotificationProvider (at KnockExpoPushNotificationProvider.tsx:267)
in KnockPushNotificationProvider (at KnockExpoPushNotificationProvider.tsx:266)
in KnockExpoPushNotificationProvider (at App.tsx:26)
in KnockI18nProvider (at …
```
> fix(KNO-8593): fix feed initialization in React Native and Expo SDKs

- .changeset/loose-dodos-rhyme.md
- packages/react-core/src/modules/slack/hooks/useSlackAuth.ts
- packages/react-core/test/slack/useSlackAuth.test.tsx
- packages/react/src/modules/slack/components/SlackAuthButton/SlackAuthButton.tsx
Changed `useSlackAuth` to:
- add new `options` param
- introduce ability to override `scopes`
- change api to break out `additionalScopes` under options
> feat: add ability to override slack scopes

- .changeset/tidy-weeks-dress.md
- packages/react/src/modules/guide/components/Banner/Banner.tsx
- packages/react/src/modules/guide/components/Card/Card.tsx
- packages/react/src/modules/guide/components/Card/styles.css
- packages/react/src/modules/guide/components/Modal/Modal.tsx
- packages/react/src/modules/guide/components/Modal/styles.css
- packages/react/src/modules/guide/components/helpers.ts
- packages/react/src/modules/guide/components/types.ts
We are adding an optional image field to the Card and Modal out-of-the-box (OOTB) message types ([here](https://github.com/knocklabs/control/pull/5057)), which means our OOTB components need to be able to render it accordingly so this PR adds an image field to the Card and Modal components.
Also related: https://github.com/knocklabs/control/pull/5073
[KNO-8613](https://linear.app/knock/issue/KNO-8613/control-add-an-image-field-to-card-and-modal-ootb-schemas)
**Card:** 
**Modal:**
> feat: support image field in modal and card components

- packages/react-core/test/feed/useNotifications.test.tsx
I’m working on refactoring the `useNotifications` hook to fix a memory leak that occurs due to the fact that the hook does not dispose of feed clients on unmount. I’m adding some test coverage to make sure I don’t break existing functionality.
> chore(KNO-8638): add tests for useNotifications hook

- .github/CODEOWNERS
- .github/dependabot.yml
This PR:
- Adds a `CODEOWNERS` file
- Removes the `reviewers` configuration option in `dependabot.yml`
See [_Dependabot reviewers configuration option being replaced by code owners_ on the GitHub blog](https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/).
> chore(KNO-8659): add CODEOWNERS file

- .github/workflows/cicd.yml
- .gitignore
- package.json
Codecov has this nice test analytics feature that I think would be useful, seems easy enough to implement too!
> Test Analytics offers data on test run times, failure rates, and identifies flaky tests to help decrease the risk of deployment failures and make it easier to ship new features quickly.
> feat: add junit reporter for more granular test coverage data

- .changeset/polite-heads-greet.md
- packages/client/src/clients/guide/client.ts
Fixes this sentry error: knock-labs-inc.sentry.io/issues/6651972538
> fix: ensure `this` is bound to guide client instance in handleLocationChange

- .changeset/spotty-plums-clap.md
- .github/workflows/release.yml
- package.json
- Updates `publish` script to correctly publish the tag that is set in the workflow
- Guards against prelease mode by throwing an error 
- Adds changeset for previous changes to test release
> fix: canary release process

- .github/workflows/release.yml
Setup the workflow to utilize `knock-eng-bot` so that it can push to main correctly.
> fix: release action prerelease use knock-eng-bot

- .changeset/short-cameras-see.md
- packages/expo/src/modules/push/KnockExpoPushNotificationProvider.tsx
As reported in #589, the `KnockExpoPushNotificationProvider` tries to process messages that don't come from knock which results in 404 errors. This PR adds a check to `updateKnockMessageStatusFromNotification` that ensures that only messages which contain `knock_message_id` are processed, the rest being ignored.
> fix: ignore messages that don't come from Knock in KnockExpoPushNotificationProvider

- .changeset/public-pants-obey.md
- packages/react/src/modules/feed/components/NotificationFeedPopover/NotificationFeedPopover.tsx
- packages/react/test/feed/NotificationFeedPopover.test.tsx
As outlined in #191, when clicking the `<NotificationIconButton/>` while the `<NotificationFeedPopover/>` component is open, the popover will reopen instead of closing. This was happening because we weren't detecting if the `closeOnOutsideClick` handler was triggered by clicking on the `<NotificationIconButton/>`. This PR adds a check to the `closeOnOutsideClick` handler to skip the `onClose` event when the `<NotificationIconButton/>` is clicked and instead let the button handle the `onClose` instead. Also, we add a test to verify this functionality.
> fix: prevent popover from reopening when clicking notification icon button

- examples/nextjs-example/pages/custom.tsx
- examples/nextjs-example/pages/index.tsx
The code in the example app still try to run if there's no id, but we need an id. So this PR puts guards in front of running that code until `useIdentify` runs.
> fix: guard against no id to fix next build

- .changeset/shaky-dolls-occur.md
- packages/react-core/src/modules/core/hooks/useAuthenticatedKnockClient.ts
Fixes an issue reported here: https://knocklabs.slack.com/archives/C079G6X3DD4/p1752604990749029
With the [recent changes](https://github.com/knocklabs/javascript/pull/626) we shipped for inline identifying a user in KnockProvider, we now take a `user` prop as an object. And this can lead to re-initializing the knock client, which causes downstream effects like re-initializing the guide client multiple times over a render cycle. 
In this PR we use `useStableOptions` for `userIdOrUserWithProperties` as it is used in the `useAuthenticatedKnockClient` hook's dep array.
> fix: unstable user prop for KnockProvider

- .changeset/plenty-ants-camp.md
- examples/nextjs-example/components/NotificationPreferences.tsx
- examples/nextjs-example/pages/preferences.tsx
- packages/react-core/src/index.ts
- packages/react-core/src/modules/preferences/hooks/index.ts
- packages/react-core/src/modules/preferences/hooks/usePreferences.ts
- packages/react-core/src/modules/preferences/index.ts
- packages/react-core/test/preferences/usePreferences.test.tsx
- packages/react/src/index.ts
- Adds `usePreferences` hook.
- Fetches preferences based on the options provided to the hook.
- Updates preferences based on the options provided to the hook.
- Allows fetching of all preferences with the `getAllPreferences` function.
- Uses SWR to simplify code. 
- Adds comprehensive tests resulting in 100% test coverage on the hook.
- Updates `@knocklabs/react` to contain export for hook.
- Adds example app for utilizing the hook.
> feat: usePreferences hook

- .github/workflows/expo.yml
Removes the no wait flag so we can actually evaluate if the expo build succeeded. This step currently isn't required to pass for PR merge because of the long build times.
> fix: remove no-wait flag from expo build action

- .changeset/chilly-needles-boil.md
- .changeset/nasty-roses-happen.md
- examples/ms-teams-connect-example/.env.sample
- examples/ms-teams-connect-example/README.md
- examples/ms-teams-connect-example/pages/index.tsx
- integration/tests/react/ms-teams/MsTeamsComponents.test.tsx
- packages/react-core/src/modules/ms-teams/hooks/useMsTeamsAuth.ts
- packages/react/src/modules/ms-teams/components/MsTeamsAuthButton/MsTeamsAuthButton.tsx
- packages/react/test/ms-teams/MsTeamsAuthButton.test.tsx
This PR renames the `msTeamsBotId` prop of `<MsTeamsAuthButton>`, and the param of the same name of the `useMsTeamsAuth` hook, to `graphApiClientId`.
This PR will only be merged after knocklabs/control#5573 is released.
> chore(KNO-9276): rename msTeamsBotId to graphApiClientId

- packages/client/src/clients/guide/client.ts
- packages/client/src/clients/guide/types.ts
- packages/client/test/clients/guide/guide.test.ts
Archiving an unthrottled guide should not affect or start the throttle window for throttled guides.
[KNO-9221](https://linear.app/knock/issue/KNO-9221/switchboard-control-guide-group-display-logging-as-a-param)
> chore: only update guide group display logs if throttled

- packages/client/src/clients/guide/client.ts
- packages/client/src/clients/guide/types.ts
- packages/client/test/clients/guide/guide.test.ts
- packages/react-core/src/modules/guide/hooks/useGuide.ts
- packages/react-core/src/modules/guide/hooks/useGuides.ts
Add the `useGuides` hook, which will return any matching selections without applying the group limit of one-at-a-time display or throttle settings.
> feat: add useGuides hook

- .changeset/fuzzy-scissors-do.md
- packages/client/src/api.ts
- packages/client/test/api.test.ts
This PR changes the user agent header from `User-Agent` to `X-Knock-Client` in the API client to better follow HTTP header conventions for custom headers. The corresponding test has been updated to reflect this change.
Users were seeing a warning in the console:
```
Refused to set unsafe header "User-Agent"
```
[From MDN docs:](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_request_header)
> Note: The User-Agent header used to be forbidden, but no longer is. However, Chrome still silently drops the header from Fetch requests (see Chromium bug 571722).
https://linear.app/knock/issue/KNO-9344/sdk-errors-caused-by-sdk-setting-user-agent-header
> fix(kno-9344): fix refused to set unsafe header "User-Agent"

- .github/workflows/cicd.yml
The `CI/CD` job wasn't being ran on the `main` branch. This meant that when codecov tried to compare test coverage to the head branch, it would have no coverage to compare to and we'd see a warning (screenshot). This PR updates the `CI/CD` job to run on a main push in addition to the previous triggers so that the head branch can be synced to codecov.
> fix: run ci/cd job on main push to sync test coverage to codecov for head branch

- examples/guide-example/src/App.tsx
- packages/client/src/clients/guide/client.ts
- packages/client/src/clients/guide/types.ts
- packages/react-core/src/modules/guide/hooks/useGuide.ts
- packages/react-core/src/modules/guide/hooks/useGuides.ts
Adds a generic type parameter for typing guide step contents, which users can pass in when using the `useGuide(s)` hooks or calling the `selecteGuide(s)` methods in the guide client.
Note, there is a corresponding CLI PR (https://github.com/knocklabs/knock-cli/pull/575) to add a new `knock guide generate-types` command which generates types for all guides in a given environment automatically.
> feat: add content type generic for guide step content

- .changeset/lemon-monkeys-hunt.md
- packages/client/src/clients/guide/client.ts
- packages/client/src/clients/guide/helpers.ts
- packages/client/src/clients/guide/types.ts
- packages/client/test/clients/guide/guide.test.ts
- packages/client/test/clients/guide/helpers.test.ts
- packages/react/src/index.ts
Add support for handling "simple" activation url rules, as configured in https://github.com/knocklabs/control/pull/5840.
Note, a guide can have either `activation_url_rules` xor `activation_url_patterns`, but not both.
> feat: add support for "simple" activation url rules

- .changeset/cruel-sides-strive.md
- packages/client/src/clients/guide/client.ts
- packages/client/src/clients/guide/index.ts
- packages/client/src/clients/guide/types.ts
- packages/client/test/clients/guide/guide.test.ts
- packages/react/src/modules/guide/components/GuideToolbar/GuideToolbar.tsx
Handles live preview update events and uses preview content if available for the given guide.
> feat: handle guides live preview content

- .changeset/lemon-zebras-judge.md
- packages/client/src/clients/guide/client.ts
- packages/client/test/clients/guide/guide.test.ts
Fixes an issue where if you only have preview guides, they wouldn't be returned. This fixes the case where you're live previewing your first guide before publishing.
> fix: return preview guides even if no published guides are present

- .changeset/ten-experts-retire.md
- packages/client/src/clients/messages/interfaces.ts
Add step_ref field corresponding to...
node SDK:
https://github.com/knocklabs/knock-node/blob/a7d10173d6b444c720b5f4941101fcce1674001d/src/resources/messages/messages.ts#L462-L465
Open API spec:
https://github.com/knocklabs/switchboard/blob/cbb39e9448b3df09cc8e0b1228de0307eb85afe7/lib/switchboard_web/specs/messages/message.ex#L131-L136
**Testing:**
Using local version of knock/client package, run the examples/client-example and verify that still works
> fix(KNO-9711): Add step_ref field to NotificationSource

- .changeset/short-masks-decide.md
- packages/client/src/knock.ts
- packages/client/test/knock.test.ts
`this.users.identify(properties)` returns a promise. This PR adds a `catch` so that we handle any rejection.
I looked into enabling [the `no-floating-promises` ESLint rule](https://typescript-eslint.io/rules/no-floating-promises/), but that requires some updates to our ESLint and TypeScript config files, so I’d like to ship this separately.
> fix(KNO-9854): handle promise rejection when identifying inline
