knocklabs/javascript

- examples/slack-connect-example/pages/index.tsx
- packages/client/src/clients/slack/index.ts
- packages/react/src/App.tsx
- packages/react/src/modules/slack/components/ConnectToSlackButton/ConnectToSlackButton.tsx
- packages/react/src/modules/slack/components/ConnectToSlackButton/styles.css
- packages/react/src/modules/slack/components/ConnectToSlackContainer/ConnectToSlackContainer.tsx
- packages/react/src/modules/slack/components/ConnectToSlackContainer/styles.css
- packages/react/src/modules/slack/components/ConnectedSlackChannelPicker/ConnectedSlackChannelPicker.tsx
- packages/react/src/modules/slack/hooks/useManageSlackConnection.ts
- packages/react/src/modules/slack/hooks/useSlackChannels.ts
Add disconnect and error states.
Product demo + code review: https://www.loom.com/share/d826accc9cda412c89d8f882d2ced267
> feat(kno-5046): Add disconnect and error states

- .changeset/cyan-rivers-explode.md
- examples/nextjs-example/pages/index.tsx
- packages/client/README.md
- packages/client/src/clients/feed/feed.ts
- packages/react/README.md
- yarn.lock
Updates the README and example app to show using the automatic socket manager. Also removes the added options from the request query params.
> fix: strip socket manager options from http requests

- .changeset/fresh-jobs-punch.md
- .prettierrc
- package.json
- packages/prettier-config/package.json
- packages/prettier-config/prettier-config.js
- yarn.lock
- Adds `@knocklabs/prettier-config` package
- Takes config from current config
- Adds `@trivago/prettier-plugin-sort-imports"` for import sort on save
- Adds prettier config to this repo
> feat: shared prettier config package

- packages/react/src/modules/slack/components/SlackChannelCombobox/AddConnectedSlackChannelInput.tsx
- packages/react/src/modules/slack/components/SlackChannelCombobox/SlackChannelCombobox.tsx
- packages/react/src/modules/slack/components/SlackChannelCombobox/SlackChannelListBox.tsx
- packages/react/src/modules/slack/components/SlackChannelCombobox/SlackChannelOption.tsx
- packages/react/src/modules/slack/components/SlackChannelCombobox/styles.css
Smooths out the loading state. https://www.loom.com/share/1cae5298b3014ac79f846e1acb6e7bd9
> fix(kno-5301): smooth out loading in comobobox

- examples/slack-connect-example/pages/index.tsx
- examples/slack-kit-example/.env.sample
- examples/slack-kit-example/app/components/slack-auth-wrapper.tsx
- examples/slack-kit-example/app/page.tsx
We do not want to hardcode the redirect url.
> fix(kno-5315): add redirect url env var

- .changeset/modern-pugs-pump.md
Adds the connected channel list component and includes it in the example apps.
> chore: connected channel changeset

- .changeset/grumpy-shirts-switch.md
- examples/slack-connect-example/pages/index.tsx
- examples/slack-kit-example/app/components/slack-auth-wrapper.tsx
- examples/slack-kit-example/app/initiate-auth/page.tsx
- packages/react/src/modules/slack/components/SlackAuthButton/SlackAuthButton.tsx
Adds the custom onAuthenticationComplete callback that accepts the results of the auth attempt for the user to handle.
> feat(kno-5364): custom onAuthenticationComplete callback for SlackAuthButton

- .changeset/quick-chicken-end.md
- packages/react-core/src/modules/feed/hooks/useNotifications.ts
- turbo.json
* Adds subscribe call back into `useNotifications` hook
> fix: re-introduce subscribe/setstate call

- .changeset/afraid-radios-retire.md
- examples/react-native-example/app.json
- examples/react-native-example/package.json
- examples/react-native-example/src/App.js
- examples/react-native-example/src/components/NotificationFeed.js
- examples/react-native-example/tsconfig.json
- packages/react-native/package.json
- packages/react-native/src/modules/push/KnockExpoPushNotificationProvider.tsx
- packages/react-native/vite.config.ts
- yarn.lock
Fixed an issue in KnockExpoPushNotificationProvider that prevented auto device token registration from working
> KnockExpoPushNotificationProvider Fix

- .changeset/bright-peaches-sin.md
- packages/client/src/clients/feed/feed.ts
- packages/client/src/clients/messages/index.ts
- packages/client/src/clients/messages/interfaces.ts
- packages/react/src/modules/feed/components/NotificationCell/NotificationCell.tsx
* Record interaction metadata on button click and cell click
* Add support for recording metadata in the client and feed methods
KNO-6669
> feat: record interaction metadata for button and container clicks

- examples/in-app-message-example/README.md
- examples/in-app-message-example/src/App.tsx
- packages/client/src/clients/in-app-message/message-client.ts
- packages/client/src/clients/in-app-message/types.ts
- packages/react-core/src/modules/in-app-message/hooks/useInAppMessages.ts
- packages/react/package.json
- packages/react/src/index.ts
- packages/react/src/modules/in-app-message/components/Banner/Banner.tsx
- packages/react/src/modules/in-app-message/components/Banner/index.ts
- packages/react/src/modules/in-app-message/components/Banner/styles.css
- packages/react/src/modules/in-app-message/components/index.ts
- packages/react/src/modules/in-app-message/components/types.ts
- packages/react/src/modules/in-app-message/index.ts
- yarn.lock
- Adds basic out of the box banner component
Very rough draft, will continue to iterate on this PR but open to high level feedback.
> feat: add out of the box banner component

- examples/in-app-message-example/src/App.tsx
- packages/client/src/clients/in-app-messages/channel-client.ts
- packages/client/src/clients/in-app-messages/message-client.ts
- packages/react-core/src/modules/in-app-message/hooks/useInAppMessages.ts
- packages/react/package.json
- packages/react/scripts/generateCssTokens.js
- packages/react/src/App.tsx
- packages/react/src/modules/in-app-message/components/Banner/Banner.tsx
- packages/react/src/modules/in-app-message/components/Banner/styles.css
- packages/react/src/modules/in-app-message/components/Card/Card.tsx
- packages/react/src/modules/in-app-message/components/Card/styles.css
- packages/react/src/modules/in-app-message/components/Modal/Modal.tsx
- packages/react/src/modules/in-app-message/components/Modal/index.ts
- packages/react/src/modules/in-app-message/components/Modal/styles.css
- packages/react/src/modules/in-app-message/components/index.ts
- packages/react/src/theme.css
- yarn.lock
- Adds modal component
- Use `knock` prefix for all classes and css variables
- Updates button styles to match designs (40px height, medium font)
Will fix the issue with the message client being re-created in another PR
> feat: add modal component

- examples/in-app-message-example/src/App.tsx
- packages/client/src/clients/in-app-messages/channel-client.ts
- packages/client/src/clients/in-app-messages/message-client.ts
- packages/react-core/src/modules/in-app-message/hooks/useInAppMessages.ts
- packages/react/package.json
- packages/react/scripts/generateCssTokens.js
- packages/react/src/App.tsx
- packages/react/src/modules/in-app-message/components/Banner/Banner.tsx
- packages/react/src/modules/in-app-message/components/Card/Card.tsx
- packages/react/src/modules/in-app-message/components/Card/index.ts
- packages/react/src/modules/in-app-message/components/Card/styles.css
- packages/react/src/modules/in-app-message/components/Modal/Modal.tsx
- packages/react/src/modules/in-app-message/components/Modal/index.ts
- packages/react/src/modules/in-app-message/components/Modal/styles.css
- packages/react/src/modules/in-app-message/components/index.ts
- packages/react/src/theme.css
- yarn.lock
Adds the Card component. Will tackle cleaning up shared utils / hooks / etc. after adding the modal.
> feat: add Card component

- .changeset/lucky-beds-smoke.md
- packages/client/src/knock.ts
- packages/react-core/src/modules/core/context/KnockProvider.tsx
- packages/react-core/src/modules/core/hooks/useAuthenticatedKnockClient.ts
- packages/react-core/src/modules/core/utils.ts
* fix: ensure userId can be null or undefined on init now
* chore: add changeset
* fix: incorrect userId type
> fix: ensure userId can be null or undefined on init now (#346)

- .changeset/wicked-buttons-care.md
- packages/react/src/modules/ms-teams/components/MsTeamsChannelCombobox/MsTeamsChannelCombobox.tsx
> fix(KNO-7839): update label of channel picker in MsTeamsChannelCombobox

- .vscode/settings.json
> chore(KNO-8355): add .vscode/settings.json file

- .github/pull_request_template.md
I based this on the PR templates we use in our other repos.
> chore(KNO-8620): add pull request template

- packages/react-core/test/core/useStableOptions.test.ts
More tests ain’t a bad thing! 😈
> chore(KNO-8648): add test for useStableOptions hook

- .changeset/cold-planets-tell.md
** Describe what, why and how of the changes clearly and concisely. Add any additional useful context or info, as necessary. **
** List any todo items necessary before merging, if any. Delete if none. **
** Attach any screenshots or recordings to visually illustrate the changes, as necessary. Delete if not relevant. **
> fix: test canary release

- .changeset/nine-mirrors-hug.md
- package.json
Somehow missed adding the build step to the release command. This fixes that 🙃
> fix: build packages before publish

- .changeset/calm-facts-jump.md
- examples/guide-example/src/App.tsx
- packages/client/src/clients/guide/client.ts
- packages/client/src/clients/guide/types.ts
- packages/client/test/clients/guide/guide.test.ts
- packages/react-core/src/modules/guide/context/KnockGuideProvider.tsx
Adds a changeset to cut a new minor bump release for the client and react packages.
Plus a few small things:
* Address feedbacks from previous reviews
* Add `throttleCheckInterval` prop to `KnockGuideProvider`
* Add `ChangelogCard` component to the guides example app
> chore: guide client pr feedbacks and changeset
